### ISSUE TITLE
!GM keeps resetting?

### ISSUE THREAD

**Issue by AnssiLaiho** [iancaragol/Feyre#1]
Hi! The Feyre Bot keeps forgetting who is the GM? Is this a bug?

**Comment by iancaragol** [comment]
Hi Anssi, about how long does it take for Feyre to forget the GM? This could certainly be a bug.

GM rolls will likely be rewritten with the new dice rolling engine I am working on

**Comment by AnssiLaiho** [comment]
We are using it for Cthulhu email game, so we are monitoring the behaviour of the !gm- functionality on daily basis... I actually thought it resets daily or somethign...  yesterday the !gm was gone in just three hours? 
(07:50 "XXX Was made GM of this channel"  10:31 "This channel does not have a dedicated GM." )

**Comment by iancaragol** [comment]
@AnssiLaiho Another user has also brought up an issue with GM rolls. I will do some investigation to try and see if this is an easy bug to fix. If not, GM rolls will be reimplemented as part of the new dice roller in the coming weeks 😄

**Comment by iancaragol** [comment]
GM roll is being removed in the rewrite
