### ISSUE TITLE
Initiative keeps getting "stuck"

### ISSUE THREAD

**Issue by nonplayer** [iancaragol/Feyre#3]
We use the bot every weekend to handle initiative in our ongoing games. We usually have 4-5 players involved, and the GM running 1-3 additional characters. Everything is super smooth except for one really annoying issue.

Every few minutes - i.e. after any single player's turn is resolved - the initiative tracker is "Stuck" and none of the emoticon buttons work. Not even the "bring to bottom" emoticon works. We have found that the _only_ way to fix it is to manually type out and run the "!init -b" command, which reloads it as expected. Afterward, the buttons work for a bit, until another few minutes pass and it gets stuck again.

**Comment by iancaragol** [comment]
Hi @nonplayer, thanks for letting me know. Ill do some investigation and see if I can find out what is causing this issue. Using emojis as buttons seems to have issues at scale as Feyre needs to constantly listen on each tracker for new emojis.

**Comment by nonplayer** [comment]
Thank you!
